### ISSUE TITLE
Attributes 'DICOMPrefix' 'FilePreamble' when initiating SOPClass

### ISSUE THREAD

**Issue by erikogabrielsson** [herrmannlab/highdicom#155]
Hi,

Highdicom sets the attribute 'DICOMPrefix' and 'FilePreamble' which is not in the pydicom dicom directory. This results in a warning by default or an exception if pydicom config.INVALID_KEYWORD_BEHAVIOR = "RAISE". I dont think you need to set those attributes as they are written by pydicoms dcmwrite?

**Comment by hackermd** [comment]
Good catch @erikogabrielsson. The behavior recently changed with the introduction of `pydicom.dataset.FileMetaDataset`. Do you want to send a PR?

**Comment by CPBridge** [comment]
@hackermd we fixed this didn't we? Can we close the issue?

**Comment by hackermd** [comment]
Indeed! We fixed this via #156 and it was included in release [0.15.1](https://github.com/herrmannlab/highdicom/releases/tag/v0.15.1)
