### ISSUE TITLE
Update import of storage class UIDs

### ISSUE THREAD

**Issue by hackermd** [herrmannlab/highdicom#160]
In the next pydicom release, storage class UIDs will become importable from `pydicom.uid` (see https://github.com/pydicom/pydicom/blob/master/pydicom/_storage_sopclass_uids.py) and the private `_storage_class_uid.py` module will be deprecated. We should consider updating highdicom once pydicom 2.3 is out.

**Comment by fedorov** [comment]
It's tangentially related, and I apologize for the distraction, but do you guys know:
1) what is the process that keeps UIDs in `pydicom.uid` in sync with the standard?
2) why there is no equivalent for `uid.AllTransferSyntaxes` for storage SOP classes?

**Comment by CPBridge** [comment]
This was addressed in #163, closing
